version: '3.3'
services:
  football_frontend: 
    container_name: football-cards_service-1
    image: abhyasgiri/service-1:latest
    build: ./service_1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 3
  nation-backend:
      container_name: football-cards_nation-backend
      image: abhyasgiri/nation-backend:latest
      build: ./service_2
      deploy:
        replicas: 3
  pack_backend:
      container_name: football-cards_pack_backend
      image: abhyasgiri/pack-backend:latest
      build: ./service_3
      deploy:
        replicas: 3
  player_backend:
      container_name: football-cards_player_backend
      image: abhyasgiri/player-backend:latest
      build: ./service_4
      deploy:
        replicas: 3
