- name: Install nginx 
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Install the nginx.conf file to the machine
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config

- name: Reload nginx
  service:
    name: nginx
    state: reloaded