---
- name: Initialise Docker Swarm
  become: true
  hosts: managers
  roles:
    - docker
    - swarm-init

- name: Add Workers to swarm
  become: true
  hosts: workers
  roles:
    - docker
    - swarm-worker

- name: Setup nginx loadbalancer
  become: true
  hosts: nginx
  roles:
    - docker
    - nginx